# fly.toml app configuration file generated for my-rewards-prod on 2024-04-13T09:29:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-rewards-prod'
primary_region = 'sjc'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DBHOST = "rewards-prod.internal"
  DBPORT = "5432"
  USERNAME = "postgres"
  PASSWORD = "7iZfhFLcnYoWsQt"
  DATABASE = "postgres" 

  #USERNAME = "my_rewards_prod"
  #PASSWORD = "fUPkGb5vhEueOOV"
  #DATABASE = "my_rewards_prod" 
  
  NODE_ENV = "development"
  ENCRYPTION_KEY = "e41c966f21f9e1577802463f8924e6a3fe3e9751f201304213b2f845d8841d61"
  SIGNATURE_KEY = 'ywljy5P2L63o6pujhH9gDQ'
  NOTIFICATION_URL = 'https://my-rewards.fly.dev/webhook'

  # Twilio settings for phone number validation
  TWILIO_ACCOUNT_SID='AC1bbfba608f9718d9230d6e6bc14f9fe7'
  TWILIO_AUTH_TOKEN='8dcca3a59cf00f3661f0ca3b2edd3a87'
  VERIFY_SERVICE_SID='VAed9207a297a5e0995db5834fb7b3f1ae'

  # JWT secret
  JWT_SECRET='AABBCCDDAABBCCDDAABBCCDDAABBCCDDAABBCCDD'
  JWT_ISSUER='ISSUER'
  JWT_AUDIENCE='AUDIENCE'

  # API prefix for endpoints
  API_PREFIX='api'