# fly.toml app configuration file generated for my-rewards-prod on 2024-04-13T09:29:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-rewards-prod'
primary_region = 'sjc'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DBHOST = "rewards-prod.internal"
  DBPORT = "5432"
  USERNAME = "postgres"
  PASSWORD = "7iZfhFLcnYoWsQt"
  DATABASE = "postgres" 

  #USERNAME = "my_rewards_prod"
  #PASSWORD = "fUPkGb5vhEueOOV"
  #DATABASE = "my_rewards_prod" 
  
  NODE_ENV = "development"
  